import React, { useEffect, useState } from "react";
import { api } from "../api";

export default function Briefing({ userId, language }) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [showSource, setShowSource] = useState(false);

  useEffect(() => {
    if (!userId) return;
    let cancelled = false;
    setLoading(true);
    api
      .getBriefing(userId, language)
      .then((r) => {
        if (!cancelled) setData(r);
      })
      .catch(() => {})
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [userId, language]);

  if (!userId) return null;
  if (loading && !data) {
    return (
      <div className="briefing">
        <div className="briefing-head">
          <span className="briefing-tag">AI briefing</span>
          <span className="footer-note">Reading your last 30 days…</span>
        </div>
      </div>
    );
  }
  if (!data) return null;

  const sourceLabel = data.source === "gemini"
    ? "Generated by Gemini · grounded in 30 days of your data · output validated"
    : data.source === "cache"
    ? "Cached briefing"
    : "Deterministic fallback (no LLM)";

  return (
    <div className="briefing" data-tour="briefing">
      <div className="briefing-head">
        <span className="briefing-tag">AI briefing</span>
        <span className="chip">{sourceLabel}</span>
      </div>
      <p className="briefing-text">{data.text}</p>
      <button
        type="button"
        className="ghost"
        onClick={() => setShowSource((v) => !v)}
      >
        {showSource ? "Hide source data" : "Show source data the model saw"}
      </button>
      {showSource && (
        <pre className="briefing-snapshot">
          {JSON.stringify(data.snapshot, null, 2)}
        </pre>
      )}
    </div>
  );
}
